import type { AgentMessage } from "@earendil-works/pi-agent-core";
import {
	type AssistantMessage,
	getCurrentSystemMessage,
	type ImageContent,
	type Message,
	type SystemMessage,
	type TextContent,
	type ToolResultMessage,
	type Usage,
	type UserMessage,
	uuidv7,
} from "@earendil-works/pi-ai";
import { randomUUID } from "crypto";
import {
	appendFileSync,
	closeSync,
	createReadStream,
	type Dirent,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readSync,
	realpathSync,
	statSync,
} from "fs";
import { dirname, join } from "path";
import { createInterface } from "readline";
import { StringDecoder } from "string_decoder";
import { APP_NAME, getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import { normalizePath, resolvePath } from "../utils/paths.ts";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";
import {
	type SessionDatabase,
	withExistingSessionDatabase,
	withSessionDatabase,
	withSessionDatabaseAsync,
} from "./session-database.ts";
import { createSessionLocator, parseSessionLocator } from "./session-locator.ts";

export { getSessionDatabasePathFromLocator, isSessionLocatorPath } from "./session-locator.ts";
export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	/** Legacy source path or opaque locator of the session this was forked from. */
	parentSession?: string;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface UsageEntry extends SessionEntryBase {
	type: "usage";
	/** Arbitrary usage category, such as "cache_warm". */
	kind: string;
	provider: string;
	model: string;
	usage: Usage;
	/** Optional human-readable qualifier for usage notices. */
	note?: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Usage from the LLM call(s) that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
	/** Complete prompt and tool state at this compaction boundary. */
	systemMessage?: SystemMessage;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** Usage from the LLM call that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/** Display-only entry recording how long the agent worked before returning to idle or another user input. */
export interface WorkDurationEntry extends SessionEntryBase {
	type: "work_duration";
	startedAt: string;
	endedAt: string;
	durationMs: number;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Content that an append-only context edit may replace without changing message metadata. */
export type ContextEditableContent =
	| UserMessage["content"]
	| AssistantMessage["content"]
	| ToolResultMessage["content"]
	| CustomMessage["content"];

/** Append-only change to one earlier entry's contribution to model context. */
export interface ContextEditEntry extends SessionEntryBase {
	type: "context_edit";
	targetId: string;
	/** Null omits the target from model context. A value replaces only its content. */
	replacement: { content: ContextEditableContent } | null;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| UsageEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| ContextEditEntry
	| LabelEntry
	| SessionInfoEntry
	| WorkDurationEntry;

/** Stored entry including the session header. */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface ProjectedSessionEntry {
	/** Raw append-only entry that owns this projected contribution. */
	sourceEntry: SessionEntry;
	/** Model-visible messages after context edits. Empty for state-only entries and omissions. */
	messages: AgentMessage[];
}

export interface SessionProjection {
	entries: ProjectedSessionEntry[];
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	/** Opaque session locator accepted by SessionManager.open(). */
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Source JSONL path for a session imported from an archive. */
	legacyPath?: string;
	/** Parent session locator or legacy JSONL path (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "buildContextEntries"
	| "buildSessionProjection"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
	| "ensureSessionDatabaseInitialized"
>;

function createSessionId(): string {
	return uuidv7();
}

export function assertValidSessionId(id: string): void {
	if (!/^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/.test(id)) {
		throw new Error(
			"Session id must be non-empty, contain only alphanumeric characters, '-', '_', and '.', and start and end with an alphanumeric character",
		);
	}
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		ids.add(entry.id);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

async function* prepareLegacyEntriesAsync(
	filePath: string,
	version: number,
	sourceHeaderJson: string,
	signal?: AbortSignal,
): AsyncGenerator<SessionEntry> {
	const ids = new Set<string>();
	const idsBySourceIndex = new Map<number, string>();
	let previousId: string | null = null;
	let sourceIndex = 0;
	let foundHeader = false;
	let processed = 0;

	for await (const entry of iterateEntriesFromFileAsync(filePath, signal)) {
		signal?.throwIfAborted();
		if (entry.type === "session") {
			if (!foundHeader) {
				foundHeader = true;
				if (JSON.stringify(entry) !== sourceHeaderJson) {
					throw new Error("Legacy session header changed while importing");
				}
			}
			sourceIndex++;
			continue;
		}

		const entrySourceIndex = sourceIndex++;
		if (version < 2) {
			entry.id = generateId(ids);
			ids.add(entry.id);
			entry.parentId = previousId;
			previousId = entry.id;
			if (entry.type === "compaction") {
				const compaction = entry as CompactionEntry & { firstKeptEntryIndex?: number };
				if (typeof compaction.firstKeptEntryIndex === "number") {
					const targetId =
						compaction.firstKeptEntryIndex === entrySourceIndex
							? entry.id
							: idsBySourceIndex.get(compaction.firstKeptEntryIndex);
					if (targetId !== undefined) compaction.firstKeptEntryId = targetId;
					delete compaction.firstKeptEntryIndex;
				}
			}
			idsBySourceIndex.set(entrySourceIndex, entry.id);
		}
		if (version < 3 && entry.type === "message") {
			const messageEntry = entry as SessionMessageEntry;
			if (messageEntry.message && (messageEntry.message as { role: string }).role === "hookMessage") {
				(messageEntry.message as { role: string }).role = "custom";
			}
		}
		yield entry;
		processed++;
		if (processed % 100 === 0) {
			await new Promise<void>((resolve) => setImmediate(resolve));
			signal?.throwIfAborted();
		}
	}
	if (!foundHeader) throw new Error("Legacy session header disappeared while importing");
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

function buildEntryIndex(entries: SessionEntry[], byId?: Map<string, SessionEntry>): Map<string, SessionEntry> {
	if (byId) return byId;
	const index = new Map<string, SessionEntry>();
	for (const entry of entries) {
		index.set(entry.id, entry);
	}
	return index;
}

function buildSessionPath(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const index = buildEntryIndex(entries, byId);
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		return [];
	}
	if (leafId) {
		leaf = index.get(leafId);
	}
	leaf ??= entries[entries.length - 1];
	if (!leaf) {
		return [];
	}

	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.push(current);
		current = current.parentId ? index.get(current.parentId) : undefined;
	}
	path.reverse();
	return path;
}

function getSessionContextSettings(path: SessionEntry[]): Pick<SessionContext, "thinkingLevel" | "model"> {
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		}
	}

	return { thinkingLevel, model };
}

/**
 * Project one selected session entry into LLM/runtime messages.
 * Plain custom entries are display/state entries and do not participate in context.
 */
export function sessionEntryToContextMessages(entry: SessionEntry): AgentMessage[] {
	if (entry.type === "message") {
		const message = entry.message;
		// Session files are parsed without validation; old versions, forks, or
		// hand-edited files can contain messages with null/missing content.
		if (message.role === "system" && message.content == null) return [{ ...message, content: "" }];
		if (
			(message.role === "user" || message.role === "assistant" || message.role === "toolResult") &&
			message.content == null
		) {
			return [{ ...message, content: [] }];
		}
		return [message];
	}
	if (entry.type === "custom_message") {
		return [
			createCustomMessage(entry.customType, entry.content ?? [], entry.display, entry.details, entry.timestamp),
		];
	}
	if (entry.type === "branch_summary" && entry.summary) {
		return [createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp)];
	}
	if (entry.type === "compaction") {
		const summary = createCompactionSummaryMessage(entry.summary, entry.tokensBefore, entry.timestamp);
		return entry.systemMessage ? [entry.systemMessage, summary] : [summary];
	}
	return [];
}

/**
 * Build the active, compaction-aware session entry list.
 *
 * This follows the current leaf path. If the path contains compaction entries,
 * the latest compaction is represented by the compaction entry itself, followed
 * by the kept entries starting at firstKeptEntryId and all entries after the
 * compaction entry. Older summarized entries are omitted.
 */
export function buildContextEntries(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const path = buildSessionPath(entries, leafId, byId);
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	if (!compaction) {
		return path;
	}

	const compactionIdx = path.findIndex((entry) => entry.id === compaction.id);
	if (compactionIdx < 0) {
		return path;
	}

	const contextEntries: SessionEntry[] = [compaction];
	let foundFirstKept = false;
	for (let i = 0; i < compactionIdx; i++) {
		const entry = path[i];
		if (entry.id === compaction.firstKeptEntryId) {
			foundFirstKept = true;
		}
		if (foundFirstKept && !(entry.type === "message" && entry.message.role === "system")) {
			contextEntries.push(entry);
		}
	}
	contextEntries.push(...path.slice(compactionIdx + 1));
	return contextEntries;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
function projectContextEntry(entry: SessionEntry, edit: ContextEditEntry | undefined): AgentMessage[] {
	const messages = sessionEntryToContextMessages(entry);
	if (!edit) return messages;
	const replacement = edit.replacement;
	if (replacement === null) return [];

	return messages.map((message) => {
		if (
			message.role !== "user" &&
			message.role !== "assistant" &&
			message.role !== "toolResult" &&
			message.role !== "custom"
		) {
			return message;
		}
		const content =
			(message.role === "assistant" || message.role === "toolResult") && typeof replacement.content === "string"
				? [{ type: "text" as const, text: replacement.content }]
				: replacement.content;
		return { ...message, content } as AgentMessage;
	});
}

/** Build provenance-preserving, compaction-aware model context. */
export function buildSessionProjection(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionProjection {
	const path = buildSessionPath(entries, leafId, byId);
	const { thinkingLevel, model } = getSessionContextSettings(path);
	const contextEntries = buildContextEntries(entries, leafId, byId);
	const edits = new Map<string, ContextEditEntry>();
	for (const entry of contextEntries) {
		if (entry.type === "context_edit") edits.set(entry.targetId, entry);
	}
	const projectedEntries = contextEntries.map(
		(sourceEntry, index): ProjectedSessionEntry => ({
			sourceEntry,
			// buildContextEntries() may retain an older compaction entry because its
			// raw ID lies inside the newest retained range. Only the newest compaction
			// at index zero contributes a checkpoint and summary.
			messages:
				sourceEntry.type === "compaction" && index > 0
					? []
					: projectContextEntry(sourceEntry, edits.get(sourceEntry.id)),
		}),
	);
	return {
		entries: projectedEntries,
		messages: projectedEntries.flatMap((entry) => entry.messages),
		thinkingLevel,
		model,
	};
}

/** Build the finalized model context from the canonical session projection. */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	const { messages, thinkingLevel, model } = buildSessionProjection(entries, leafId, byId);
	return { messages, thinkingLevel, model };
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pi/agent/sessions/.
 */
function getDefaultSessionDirPath(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const resolvedCwd = resolvePath(cwd);
	const resolvedAgentDir = resolvePath(agentDir);
	const safePath = `--${resolvedCwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	return join(resolvedAgentDir, "sessions", safePath);
}

export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = getDefaultSessionDirPath(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

const SESSION_READ_BUFFER_SIZE = 1024 * 1024;
const SESSION_HEADER_READ_BUFFER_SIZE = 4096;
/** Bound synchronous header discovery while allowing large cwd and custom metadata fields. */
const MAX_SESSION_HEADER_SCAN_BYTES = 1024 * 1024;

class SessionHeaderScanLimitError extends Error {
	constructor(filePath: string) {
		super(`Session header exceeds ${MAX_SESSION_HEADER_SCAN_BYTES}-byte scan limit: ${filePath}`);
		this.name = "SessionHeaderScanLimitError";
	}
}

function parseSessionEntryLine(line: string): FileEntry | undefined {
	if (!line.trim()) return undefined;
	const parsed: unknown = JSON.parse(line);
	if (
		typeof parsed !== "object" ||
		parsed === null ||
		Array.isArray(parsed) ||
		typeof (parsed as { type?: unknown }).type !== "string"
	) {
		throw new Error("Invalid session JSONL entry: expected an object with a string type");
	}
	return parsed as FileEntry;
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string, repairTrailingNewline = true): FileEntry[] {
	const resolvedFilePath = normalizePath(filePath);
	if (!existsSync(resolvedFilePath)) return [];

	const entries: FileEntry[] = [];
	let pending = "";
	const fd = openSync(resolvedFilePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);

		while (true) {
			const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
			if (bytesRead === 0) break;

			pending += decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = pending.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				const entry = parseSessionEntryLine(pending.slice(lineStart, newlineIndex));
				if (entry) entries.push(entry);
				lineStart = newlineIndex + 1;
				newlineIndex = pending.indexOf("\n", lineStart);
			}
			pending = pending.slice(lineStart);
		}

		pending += decoder.end();
		const finalEntry = parseSessionEntryLine(pending);
		if (finalEntry) entries.push(finalEntry);
	} finally {
		closeSync(fd);
	}

	// Validate session header before repairing the file.
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof (header as { id?: unknown }).id !== "string") {
		return [];
	}

	if (pending && repairTrailingNewline) appendFileSync(resolvedFilePath, "\n");
	return entries;
}

const LEGACY_JSONL_IMPORT_KEY = "legacy-jsonl-import-v3";
const DEFAULT_SESSION_DATABASE_FILENAME = "sessions.db";

function getSessionDatabasePath(sessionDir?: string): string {
	return sessionDir
		? join(normalizePath(sessionDir), DEFAULT_SESSION_DATABASE_FILENAME)
		: join(getDefaultAgentDir(), DEFAULT_SESSION_DATABASE_FILENAME);
}
function collectLegacySessionFiles(directory: string, depth: number): string[] {
	const files: string[] = [];
	let entries: Dirent[];
	try {
		entries = readdirSync(directory, { withFileTypes: true });
	} catch (error) {
		if (error instanceof Error && "code" in error && error.code === "ENOENT") return files;
		throw new Error(`Failed to discover legacy sessions in ${directory}`, { cause: error });
	}

	for (const entry of entries) {
		const path = join(directory, entry.name);
		let isFile = entry.isFile();
		let isDirectory = entry.isDirectory();
		if (entry.isSymbolicLink()) {
			try {
				const target = statSync(path);
				isFile = target.isFile();
				isDirectory = target.isDirectory();
			} catch (error) {
				if (error instanceof Error && "code" in error && error.code === "ENOENT") continue;
				throw new Error(`Failed to inspect legacy session symlink ${path}`, { cause: error });
			}
		}
		if (isFile && entry.name.endsWith(".jsonl")) {
			files.push(path);
		} else if (depth > 0 && isDirectory) {
			files.push(...collectLegacySessionFiles(path, depth - 1));
		}
	}
	return files;
}

async function* iterateEntriesFromFileAsync(
	filePath: string,
	signal: AbortSignal | undefined,
	onReadProgress: (bytesRead: number) => void = () => {},
): AsyncGenerator<FileEntry> {
	const input = createReadStream(normalizePath(filePath), { encoding: "utf8", signal });
	const lines = createInterface({ input, crlfDelay: Infinity });
	let linesSinceYield = 0;
	try {
		for await (const line of lines) {
			signal?.throwIfAborted();
			const entry = parseSessionEntryLine(line);
			if (entry) yield entry;
			linesSinceYield++;
			if (linesSinceYield >= 100) {
				linesSinceYield = 0;
				onReadProgress(input.bytesRead);
				await new Promise<void>((resolve) => setImmediate(resolve));
				signal?.throwIfAborted();
			}
		}
		signal?.throwIfAborted();
		onReadProgress(input.bytesRead);
	} finally {
		lines.close();
		input.destroy();
	}
}

async function loadEntriesFromFileAsync(
	filePath: string,
	signal: AbortSignal | undefined,
	onReadProgress: (bytesRead: number) => void,
): Promise<FileEntry[]> {
	const entries: FileEntry[] = [];
	for await (const entry of iterateEntriesFromFileAsync(filePath, signal, onReadProgress)) entries.push(entry);
	return entries;
}

async function scanLegacyArchiveAsync(
	filePath: string,
	signal: AbortSignal | undefined,
	onReadProgress: (bytesRead: number) => void,
): Promise<{ header?: SessionHeader; totalEntries: number }> {
	let header: SessionHeader | undefined;
	let totalEntries = 0;
	for await (const entry of iterateEntriesFromFileAsync(filePath, signal, onReadProgress)) {
		if (entry.type === "session") {
			header ??= entry as SessionHeader;
		} else {
			totalEntries++;
		}
	}
	return { header, totalEntries };
}

async function initializeSessionDatabase(
	databasePath: string,
	sessionDir: string,
	onProgress?: SessionListProgress,
	signal?: AbortSignal,
): Promise<void> {
	signal?.throwIfAborted();
	const resolvedDatabasePath = resolvePath(databasePath);
	const isComplete = withSessionDatabase(
		resolvedDatabasePath,
		(database) => database.getMetadata(LEGACY_JSONL_IMPORT_KEY) === "complete",
	);
	if (isComplete) return;

	const files = collectLegacySessionFilesForDatabase(resolvedDatabasePath, sessionDir).map((path) => ({
		path,
		size: statSync(path).size,
	}));
	const totalBytes = files.reduce((total, file) => total + file.size, 0);
	let completedBytes = 0;
	for (const { path, size } of files) {
		signal?.throwIfAborted();
		try {
			const { header, totalEntries } = await scanLegacyArchiveAsync(path, signal, (bytesRead) => {
				onProgress?.(completedBytes + Math.min(bytesRead, size), totalBytes, undefined, "reading");
			});
			await new Promise<void>((resolve) => setImmediate(resolve));
			signal?.throwIfAborted();
			if (header) {
				const version = header.version ?? 1;
				const sourceHeaderJson = JSON.stringify(header);
				if (version < CURRENT_SESSION_VERSION) header.version = CURRENT_SESSION_VERSION;
				await withSessionDatabaseAsync(resolvedDatabasePath, (database) =>
					database.importSessionAsync(
						header,
						prepareLegacyEntriesAsync(path, version, sourceHeaderJson, signal),
						totalEntries,
						path,
						signal,
						(loaded, total) => onProgress?.(loaded, total, undefined, "writing"),
					),
				);
			}
		} catch (error) {
			// Cancellation is user control flow; preserve AbortError rather than wrapping it as an import failure.
			if (signal?.aborted) signal.throwIfAborted();
			throw new Error(`Failed to import legacy session archive ${path}`, { cause: error });
		}
		completedBytes += size;
		onProgress?.(completedBytes, totalBytes, undefined, "reading");
	}
	signal?.throwIfAborted();
	withSessionDatabase(resolvedDatabasePath, (database) => database.setMetadata(LEGACY_JSONL_IMPORT_KEY, "complete"));
}

function getStoredSession(databasePath: string, sessionId: string, cwd?: string): FileEntry[] | undefined {
	return withExistingSessionDatabase(
		databasePath,
		(database) => database.readSession(sessionId, cwd) as FileEntry[] | undefined,
	);
}

/** Check whether an opaque session locator refers to an active stored session. */
export function hasStoredSessionLocator(value: string): boolean {
	const locator = parseSessionLocator(value);
	return locator
		? withExistingSessionDatabase(locator.databasePath, (database) =>
				database.hasSession(locator.sessionId, locator.cwd),
			)
		: false;
}

/**
 * Inspect a physical line while searching for the first parsed session entry.
 * Blank lines are skipped; malformed JSON propagates as a parse error.
 * Returns undefined to keep scanning, null for a parsed non-header entry, or the header.
 */
function parseSessionHeaderCandidate(line: string): SessionHeader | null | undefined {
	if (!line.trim()) return undefined;
	const entry = parseSessionEntryLine(line);
	if (!entry) return undefined;
	if (entry.type !== "session" || typeof (entry as { id?: unknown }).id !== "string") return null;
	return entry;
}

function readSessionHeader(filePath: string): SessionHeader | null {
	const fd = openSync(filePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_HEADER_READ_BUFFER_SIZE);
		const lineChunks: string[] = [];
		let scannedBytes = 0;

		while (scannedBytes < MAX_SESSION_HEADER_SCAN_BYTES) {
			const readLength = Math.min(buffer.length, MAX_SESSION_HEADER_SCAN_BYTES - scannedBytes);
			const bytesRead = readSync(fd, buffer, 0, readLength, null);
			if (bytesRead === 0) {
				lineChunks.push(decoder.end());
				return parseSessionHeaderCandidate(lineChunks.join("")) ?? null;
			}
			scannedBytes += bytesRead;

			const chunk = decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = chunk.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				lineChunks.push(chunk.slice(lineStart, newlineIndex));
				const header = parseSessionHeaderCandidate(lineChunks.join(""));
				if (header !== undefined) return header;
				lineChunks.length = 0;
				lineStart = newlineIndex + 1;
				newlineIndex = chunk.indexOf("\n", lineStart);
			}
			lineChunks.push(chunk.slice(lineStart));
		}

		// Probe for EOF so a final header without a newline is allowed when it ends
		// exactly at the scan limit. Any additional byte exceeds the bounded scan.
		const probe = Buffer.allocUnsafe(1);
		if (readSync(fd, probe, 0, probe.length, null) === 0) {
			lineChunks.push(decoder.end());
			return parseSessionHeaderCandidate(lineChunks.join("")) ?? null;
		}
		throw new SessionHeaderScanLimitError(filePath);
	} finally {
		closeSync(fd);
	}
}

function collectLegacySessionFilesForDatabase(databasePath: string, sessionDir: string): string[] {
	const isDefaultDatabase = resolvePath(databasePath) === resolvePath(getSessionDatabasePath());
	const files = isDefaultDatabase
		? [...collectLegacySessionFiles(getDefaultAgentDir(), 0), ...collectLegacySessionFiles(getSessionsDir(), 1)]
		: [...collectLegacySessionFiles(sessionDir, 0), ...collectLegacySessionFiles(join(sessionDir, "sessions"), 1)];
	const seenArchives = new Set<string>();
	return files.filter((file) => {
		const canonicalPath = realpathSync(file);
		if (seenArchives.has(canonicalPath)) return false;
		seenArchives.add(canonicalPath);
		return true;
	});
}

function findLegacySessionIdConflict(
	databasePath: string,
	sessionDir: string,
	cwd: string,
	sessionId: string,
): string | undefined {
	const resolvedCwd = resolvePath(cwd);
	for (const path of collectLegacySessionFilesForDatabase(databasePath, sessionDir)) {
		const header = readSessionHeader(path);
		if (
			header?.id === sessionId &&
			typeof header.cwd === "string" &&
			header.cwd.length > 0 &&
			resolvePath(header.cwd) === resolvedCwd
		) {
			return path;
		}
	}
	return undefined;
}

function getSessionHeaderCwd(header: SessionHeader): string | undefined {
	const cwd = (header as { cwd?: unknown }).cwd;
	return typeof cwd === "string" ? cwd : undefined;
}

function sessionCwdMatches(
	cwd: string | undefined,
	resolvedCwd: string,
	legacyPath?: string,
	legacyAgentDir?: string,
): boolean {
	if (cwd) return resolvePath(cwd) === resolvedCwd;
	if (!legacyPath) return false;
	return resolvePath(dirname(legacyPath)) === resolvePath(getDefaultSessionDirPath(resolvedCwd, legacyAgentDir));
}

/** Import progress reports bytes while reading and entries while writing; listing progress reports sessions. */
export type SessionListProgress = (
	loaded: number,
	total: number,
	/** Sessions loaded so far, sorted by activity. Present on periodic updates. */
	partialSessions?: readonly SessionInfo[],
	stage?: "reading" | "writing" | "listing",
) => void;

const CURRENT_SESSION_LIST_PUBLISH_INTERVAL = 10;
const ALL_SESSION_LIST_PUBLISH_INTERVAL = 100;

function sortSessionInfos(sessions: SessionInfo[]): SessionInfo[] {
	return sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
}

async function readSessionInfos(
	databasePath: string,
	sessionDir: string,
	cwd?: string,
	onProgress?: SessionListProgress,
	signal?: AbortSignal,
): Promise<SessionInfo[]> {
	await initializeSessionDatabase(databasePath, sessionDir, onProgress, signal);
	signal?.throwIfAborted();
	const sessions = withSessionDatabase(databasePath, (database) => {
		const rows =
			cwd === undefined
				? database.listSessions()
				: database.listSessions(cwd, getDefaultSessionDirPath(cwd, sessionDir));
		return rows.map((session) => ({
			...session,
			path: createSessionLocator(databasePath, session.id, session.cwd),
		}));
	});
	const locatorByLegacyPath = new Map<string, string>();
	for (const session of sessions) {
		if (session.legacyPath) locatorByLegacyPath.set(resolvePath(session.legacyPath), session.path);
	}
	return sessions.map((session) => {
		const parentPath = session.parentSessionPath;
		if (!parentPath || parseSessionLocator(parentPath)) return session;
		const parentLocator = locatorByLegacyPath.get(resolvePath(parentPath));
		return parentLocator ? { ...session, parentSessionPath: parentLocator } : session;
	});
}

function publishSessionList(
	sessions: SessionInfo[],
	onProgress: SessionListProgress | undefined,
	signal: AbortSignal | undefined,
	interval: number,
): SessionInfo[] {
	const partial: SessionInfo[] = [];
	for (let index = 0; index < sessions.length; index++) {
		signal?.throwIfAborted();
		partial.push(sessions[index]!);
		const loaded = index + 1;
		if (loaded === 1 || loaded % interval === 0 || loaded === sessions.length) {
			onProgress?.(loaded, sessions.length, sortSessionInfos([...partial]), "listing");
			signal?.throwIfAborted();
		}
	}
	return sessions;
}

/**
 * Manages conversation sessions as append-only trees stored in a local Turso database.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private databasePath: string | undefined;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		newSessionOptions?: NewSessionOptions,
		preloadedFileEntries?: FileEntry[],
		databasePath?: string,
	) {
		this.cwd = resolvePath(cwd);
		this.sessionDir = normalizePath(sessionDir);
		this.persist = persist;
		if (persist) {
			this.databasePath = resolvePath(databasePath ?? getSessionDatabasePath());
		}

		if (sessionFile) {
			this._setSessionFile(sessionFile, preloadedFileEntries);
		} else if (preloadedFileEntries?.length) {
			this._loadEntries(preloadedFileEntries, newSessionOptions);
		} else {
			this.newSession(newSessionOptions);
		}
	}

	/** Switch to a session locator or import a legacy JSONL file. */
	setSessionFile(sessionFile: string): void {
		this._setSessionFile(sessionFile);
	}

	private _setSessionFile(sessionFile: string, preloadedFileEntries?: FileEntry[]): void {
		const locator = parseSessionLocator(sessionFile);
		if (locator) {
			const entries = getStoredSession(locator.databasePath, locator.sessionId, locator.cwd);
			if (!entries) throw new Error(`Session not found in local database: ${locator.sessionId}`);
			const header = entries.find((entry) => entry.type === "session") as SessionHeader | undefined;
			this.databasePath = locator.databasePath;
			this.sessionDir = dirname(locator.databasePath);
			this.sessionFile = createSessionLocator(
				locator.databasePath,
				locator.sessionId,
				header?.cwd ?? locator.cwd ?? this.cwd,
			);
			this._loadEntries(entries);
			this.flushed = true;
			return;
		}

		const explicitPath = resolvePath(sessionFile);
		if (!existsSync(explicitPath)) throw new Error(`Session file not found: ${explicitPath}`);
		const entries = preloadedFileEntries ?? loadEntriesFromFile(explicitPath, false);
		if (entries.length === 0) {
			if (statSync(explicitPath).size === 0) throw new Error(`Session file is empty: ${explicitPath}`);
			throw new Error(`Session file is not a valid ${APP_NAME} session: ${explicitPath}`);
		}

		const header = entries.find((entry) => entry.type === "session") as SessionHeader | undefined;
		if (!header) throw new Error(`Session file is not a valid ${APP_NAME} session: ${explicitPath}`);
		migrateToCurrentVersion(entries);
		const databasePath = this.databasePath ?? getSessionDatabasePath(this.sessionDir);
		this.databasePath = databasePath;
		const sessionCwd = typeof header.cwd === "string" ? header.cwd : "";
		const sessionEntries = entries.filter((entry): entry is SessionEntry => entry.type !== "session");
		const importResult = withSessionDatabase(databasePath, (database) =>
			database.importSession(header, sessionEntries, explicitPath),
		);
		if (importResult === "deleted") throw new Error(`Cannot open deleted legacy session archive: ${explicitPath}`);
		const storedEntries = getStoredSession(databasePath, header.id, sessionCwd) ?? entries;
		this.sessionFile = createSessionLocator(databasePath, header.id, sessionCwd);
		this._loadEntries(storedEntries);
		this.flushed = true;
	}

	newSession(options?: NewSessionOptions): string | undefined {
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
			if (this.persist && this.databasePath) {
				if (
					withSessionDatabase(
						this.databasePath,
						(database) =>
							database.hasSession(options.id!, this.cwd) || database.hasDeletedSession(options.id!, this.cwd),
					)
				) {
					throw new Error(`Session id already exists: ${options.id}`);
				}
				const legacyArchive = findLegacySessionIdConflict(this.databasePath, this.sessionDir, this.cwd, options.id);
				if (legacyArchive) {
					throw new Error(`Session id already exists: ${options.id} (legacy archive: ${legacyArchive})`);
				}
			}
		}
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		this.flushed = false;

		if (this.persist) {
			this.sessionFile = createSessionLocator(
				this.databasePath ?? getSessionDatabasePath(),
				this.sessionId,
				this.cwd,
			);
		}
		return this.sessionFile;
	}

	private _loadEntries(entries: FileEntry[], options?: NewSessionOptions): void {
		const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;

		if (header) {
			this.fileEntries = entries;
			this.sessionId = header.id;

			if (migrateToCurrentVersion(this.fileEntries)) {
				this._rewriteFile();
			}
		} else {
			this.newSession(options);
			this.fileEntries = this.fileEntries.concat(entries);
		}

		this._buildIndex();
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			this.leafId = entry.id;
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			}
		}
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.databasePath) return;
		const header = this.getHeader();
		if (!header) return;
		withSessionDatabase(this.databasePath, (database) => database.writeSession(header, this.getEntries()));
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	usesDefaultSessionDir(): boolean {
		return this.databasePath === getSessionDatabasePath();
	}

	getSessionId(): string {
		return this.sessionId;
	}

	/** Opaque session locator accepted by SessionManager.open(). */
	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	/** Local Turso database file containing this session. */
	getSessionDatabasePath(): string | undefined {
		return this.databasePath;
	}

	/** Ensure session search can read the database, importing legacy archives if needed. */
	async ensureSessionDatabaseInitialized(onProgress?: SessionListProgress, signal?: AbortSignal): Promise<void> {
		if (!this.persist || !this.databasePath) return;
		await initializeSessionDatabase(this.databasePath, this.sessionDir, onProgress, signal);
	}

	/** Whether this session has been flushed to persistent storage. */
	hasStoredSession(): boolean {
		const locator = this.sessionFile ? parseSessionLocator(this.sessionFile) : undefined;
		const cwd = locator?.cwd ?? this.getHeader()?.cwd ?? this.cwd;
		if (!this.persist || !this.databasePath) return false;
		const read = (database: SessionDatabase) => database.hasSession(this.sessionId, cwd);
		return this.flushed
			? withExistingSessionDatabase(this.databasePath, read)
			: withSessionDatabase(this.databasePath, read);
	}

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.databasePath) return;

		const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
		if (!hasAssistant) {
			if (this.flushed) {
				const header = this.getHeader();
				if (header) {
					withSessionDatabase(this.databasePath, (database) => database.appendEntry(header, entry));
				}
			} else {
				// Defer storing an empty session until an assistant reply exists.
			}
			return;
		}

		if (!this.flushed) {
			const header = this.getHeader();
			if (header)
				withSessionDatabase(this.databasePath, (database) => database.createSession(header, this.getEntries()));
			this.flushed = true;
		} else {
			const header = this.getHeader();
			if (header) {
				withSessionDatabase(this.databasePath, (database) => database.appendEntry(header, entry));
			}
		}
	}

	private _appendEntry(entry: SessionEntry): void {
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		this._persist(entry);
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append model-attributed usage that does not participate in LLM context. Returns the appended entry. */
	appendUsage(kind: string, provider: string, model: string, usage: Usage, note?: string): UsageEntry {
		const entry: UsageEntry = {
			type: "usage",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			kind,
			provider,
			model,
			usage,
			...(note ? { note } : {}),
		};
		this._appendEntry(entry);
		return entry;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string | null,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		const timestamp = new Date().toISOString();
		const systemMessage = getCurrentSystemMessage(this.buildSessionProjection().messages);
		const id = generateId(this.byId);
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id,
			parentId: this.leafId,
			timestamp,
			summary,
			firstKeptEntryId: firstKeptEntryId ?? id,
			tokensBefore,
			details,
			usage,
			fromHook,
			...(systemMessage ? { systemMessage: { ...systemMessage, timestamp: new Date(timestamp).getTime() } } : {}),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const sanitizedName = name.replace(/[\r\n]+/g, " ").trim();
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: sanitizedName,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a display-only agent work duration entry. Returns entry id. */
	appendWorkDuration(startedAtMs: number, endedAtMs: number): string {
		const durationMs = Math.max(0, Math.round(endedAtMs - startedAtMs));
		const entry: WorkDurationEntry = {
			type: "work_duration",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date(endedAtMs).toISOString(),
			startedAt: new Date(startedAtMs).toISOString(),
			endedAt: new Date(endedAtMs).toISOString(),
			durationMs,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		// Walk entries in reverse to find the latest session_info entry.
		// Empty names explicitly clear the session title.
		const entries = this.getEntries();
		for (let i = entries.length - 1; i >= 0; i--) {
			const entry = entries[i];
			if (entry.type === "session_info") {
				return entry.name?.trim() || undefined;
			}
		}
		return undefined;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a branch-local edit to an earlier model-visible entry. */
	appendContextEdit(targetId: string, replacement: ContextEditEntry["replacement"]): string {
		if (
			replacement !== null &&
			(typeof replacement !== "object" ||
				!("content" in replacement) ||
				(typeof replacement.content !== "string" && !Array.isArray(replacement.content)))
		) {
			throw new Error("Context edit replacement must be null or contain string/array content");
		}
		const target = this.byId.get(targetId);
		if (!target) throw new Error(`Entry ${targetId} not found`);
		if (!this.getBranch().some((entry) => entry.id === targetId)) {
			throw new Error(`Entry ${targetId} is not on the active branch`);
		}
		const editable =
			target.type === "custom_message" ||
			(target.type === "message" &&
				(target.message.role === "user" ||
					target.message.role === "assistant" ||
					target.message.role === "toolResult"));
		if (!editable) throw new Error(`Entry ${targetId} does not contribute editable model content`);
		const targetRole = target.type === "message" ? target.message.role : "custom";
		const normalizedReplacement =
			replacement !== null &&
			(targetRole === "assistant" || targetRole === "toolResult") &&
			typeof replacement.content === "string"
				? { content: [{ type: "text" as const, text: replacement.content }] }
				: replacement;
		const entry: ContextEditEntry = {
			type: "context_edit",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			replacement: normalizedReplacement,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		while (current) {
			path.push(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		path.reverse();
		return path;
	}

	/**
	 * Build the active, compaction-aware entry list for context/rendering.
	 * Uses tree traversal from current leaf.
	 */
	buildContextEntries(): SessionEntry[] {
		return buildContextEntries(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionProjection(): SessionProjection {
		return buildSessionProjection(this.getEntries(), this.leafId, this.byId);
	}

	buildSessionContext(): SessionContext {
		const { messages, thinkingLevel, model } = this.buildSessionProjection();
		return { messages, thinkingLevel, model };
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header). Returns a shallow copy.
	 * The session is append-only: use appendXXX() to add entries, branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 */
	getEntries(): SessionEntry[] {
		return this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(
		branchFromId: string | null,
		summary: string,
		details?: unknown,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		const fromId = this.leafId ?? "root";
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId,
			summary,
			details,
			usage,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Create a new database session containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session locator, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const previousSessionFile = this.sessionFile;
		const path = this.getBranch(leafId);
		if (path.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		// Filter out LabelEntry from path - we'll recreate them from the resolved map.
		// Because labels are real tree entries, later entries can be children of labels;
		// removing labels requires re-chaining the retained path to avoid orphaned subtrees.
		const pathWithoutLabels: SessionEntry[] = [];
		const replacementByLabelId = new Map<string, string>();
		const pendingLabelIds: string[] = [];
		let pathParentId: string | null = null;
		for (const entry of path) {
			if (entry.type === "label") {
				pendingLabelIds.push(entry.id);
				continue;
			}
			for (const labelId of pendingLabelIds) {
				replacementByLabelId.set(labelId, entry.id);
			}
			pendingLabelIds.length = 0;
			pathWithoutLabels.push(
				entry.type === "compaction"
					? {
							...entry,
							parentId: pathParentId,
							firstKeptEntryId:
								entry.firstKeptEntryId === entry.id
									? entry.id
									: (replacementByLabelId.get(entry.firstKeptEntryId) ?? entry.firstKeptEntryId),
						}
					: { ...entry, parentId: pathParentId },
			);
			pathParentId = entry.id;
		}

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const newSessionFile =
			this.persist && this.databasePath
				? createSessionLocator(this.databasePath, newSessionId, this.cwd)
				: undefined;

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = newSessionId;
			this.sessionFile = newSessionFile;
			this._buildIndex();

			// Defer inserting sessions without an assistant response, matching newSession().
			const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
			if (hasAssistant) {
				if (this.databasePath) {
					withSessionDatabase(this.databasePath, (database) => database.createSession(header, this.getEntries()));
				}
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = newSessionId;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session in the shared local database.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional database directory. If omitted, uses ~/.pi/agent/sessions.db.
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultAgentDir();
		return new SessionManager(cwd, dir, undefined, true, options, undefined, getSessionDatabasePath(sessionDir));
	}

	/**
	 * Open a session locator or import a legacy JSONL session into the local database.
	 * @param path Session locator or legacy JSONL path
	 * @param sessionDir Optional database directory for /new or /branch.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(path: string, sessionDir?: string, cwdOverride?: string): SessionManager {
		const locator = parseSessionLocator(path);
		const resolvedPath = locator ? path : resolvePath(path);
		let header: SessionHeader | null = null;
		let preloadedFileEntries: FileEntry[] | undefined;
		if (locator) {
			const entries = getStoredSession(locator.databasePath, locator.sessionId, locator.cwd);
			const firstEntry = entries?.[0];
			header = firstEntry?.type === "session" ? firstEntry : null;
		} else if (cwdOverride === undefined && existsSync(resolvedPath)) {
			try {
				header = readSessionHeader(resolvedPath);
			} catch (error) {
				if (!(error instanceof SessionHeaderScanLimitError)) throw error;
				// The bounded scan is only a discovery optimization. A full load remains
				// authoritative for legacy files with very large headers or prefixes.
				preloadedFileEntries = loadEntriesFromFile(resolvedPath, false);
				const firstEntry = preloadedFileEntries[0];
				header = firstEntry?.type === "session" ? firstEntry : null;
			}
		}
		const cwd = cwdOverride ?? (header ? getSessionHeaderCwd(header) : undefined) ?? process.cwd();
		const databasePath = locator?.databasePath ?? getSessionDatabasePath(sessionDir);
		const dir = locator
			? dirname(locator.databasePath)
			: sessionDir
				? normalizePath(sessionDir)
				: getDefaultAgentDir();
		return new SessionManager(cwd, dir, resolvedPath, true, undefined, preloadedFileEntries, databasePath);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional database directory. If omitted, uses ~/.pi/agent/sessions.db.
	 */
	static async continueRecent(cwd: string, sessionDir?: string): Promise<SessionManager> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultAgentDir();
		const databasePath = getSessionDatabasePath(sessionDir);
		const resolvedCwd = resolvePath(cwd);
		const sessions = await readSessionInfos(databasePath, dir, resolvedCwd);
		const mostRecent = sessions.find((session) =>
			sessionCwdMatches(session.cwd, resolvedCwd, session.legacyPath, dir),
		);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent.path, true, undefined, undefined, databasePath);
		}
		return new SessionManager(cwd, dir, undefined, true, undefined, undefined, databasePath);
	}

	/** Create an in-memory session (no file persistence), optionally from entries held outside the filesystem. */
	static inMemory(cwd: string = process.cwd(), options?: NewSessionOptions, entries?: FileEntry[]): SessionManager {
		return new SessionManager(cwd, "", undefined, false, options, entries);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new database session in the target cwd with the source session's full history.
	 * @param sourcePath Session locator or legacy JSONL file path
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional database directory. If omitted, uses ~/.pi/agent/sessions.db.
	 */
	static async forkFrom(
		sourcePath: string,
		targetCwd: string,
		sessionDir?: string,
		options?: NewSessionOptions,
	): Promise<SessionManager> {
		const sourceLocator = parseSessionLocator(sourcePath);
		const resolvedSourcePath = sourceLocator ? sourcePath : resolvePath(sourcePath);
		const resolvedTargetCwd = resolvePath(targetCwd);
		const sourceEntries = sourceLocator
			? (getStoredSession(sourceLocator.databasePath, sourceLocator.sessionId, sourceLocator.cwd) ?? [])
			: await loadEntriesFromFileAsync(resolvedSourcePath, undefined, () => {});
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session is empty or invalid: ${resolvedSourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${resolvedSourcePath}`);
		}
		migrateToCurrentVersion(sourceEntries);

		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultAgentDir();
		const databasePath = getSessionDatabasePath(sessionDir);
		await initializeSessionDatabase(databasePath, dir);

		// Create a new database session with a new ID and copied entries.
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		const newSessionId = options?.id ?? createSessionId();
		if (withSessionDatabase(databasePath, (database) => database.hasSession(newSessionId, resolvedTargetCwd))) {
			throw new Error(`Session id already exists: ${newSessionId}`);
		}
		const timestamp = new Date().toISOString();
		const newSessionFile = createSessionLocator(databasePath, newSessionId, resolvedTargetCwd);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: resolvedTargetCwd,
			parentSession: resolvedSourcePath,
		};
		const sessionEntries = sourceEntries.filter((entry): entry is SessionEntry => entry.type !== "session");
		withSessionDatabase(databasePath, (database) => database.createSession(newHeader, sessionEntries));
		return new SessionManager(resolvedTargetCwd, dir, newSessionFile, true, undefined, undefined, databasePath);
	}

	/**
	 * Find an exact session ID by project cwd after importing legacy archives.
	 * @param cwd Working directory
	 * @param id Exact session ID
	 * @param sessionDir Optional database directory. If omitted, uses ~/.pi/agent/sessions.db.
	 */
	static async findById(cwd: string, id: string, sessionDir?: string): Promise<string | undefined> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultAgentDir();
		const databasePath = getSessionDatabasePath(sessionDir);
		const resolvedCwd = resolvePath(cwd);
		await initializeSessionDatabase(databasePath, dir);
		const match = withSessionDatabase(databasePath, (database) =>
			database
				.findSessionsById(id)
				.find((session) => sessionCwdMatches(session.cwd, resolvedCwd, session.legacy_path ?? undefined, dir)),
		);
		return match ? createSessionLocator(databasePath, match.id, match.cwd) : undefined;
	}

	/** Delete one persisted session from its local Turso database. */
	static delete(path: string): boolean {
		const locator = parseSessionLocator(path);
		if (!locator) throw new Error("Only Turso session locators can be deleted");
		return withExistingSessionDatabase(locator.databasePath, (database) =>
			database.deleteSession(locator.sessionId, locator.cwd),
		);
	}

	/** Restore a session moved to the database's trash table. */
	static restoreDeleted(path: string): boolean {
		const locator = parseSessionLocator(path);
		if (!locator) throw new Error("Only Turso session locators can be restored");
		return withExistingSessionDatabase(locator.databasePath, (database) =>
			database.restoreSession(locator.sessionId, locator.cwd),
		);
	}

	/**
	 * List sessions for one project cwd.
	 * @param cwd Working directory
	 * @param sessionDir Optional database directory. If omitted, uses ~/.pi/agent/sessions.db.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(
		cwd: string,
		sessionDir?: string,
		onProgress?: SessionListProgress,
		signal?: AbortSignal,
	): Promise<SessionInfo[]> {
		signal?.throwIfAborted();
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultAgentDir();
		const databasePath = getSessionDatabasePath(sessionDir);
		const resolvedCwd = resolvePath(cwd);
		const sessions = await readSessionInfos(databasePath, dir, resolvedCwd, onProgress, signal);
		const filtered = sessions.filter((session) =>
			sessionCwdMatches(session.cwd, resolvedCwd, session.legacyPath, dir),
		);
		publishSessionList(filtered, onProgress, signal, CURRENT_SESSION_LIST_PUBLISH_INTERVAL);
		return sortSessionInfos(filtered);
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress, signal?: AbortSignal): Promise<SessionInfo[]>;
	static async listAll(
		sessionDir?: string,
		onProgress?: SessionListProgress,
		signal?: AbortSignal,
	): Promise<SessionInfo[]>;
	static async listAll(
		sessionDirOrOnProgress?: string | SessionListProgress,
		onProgressOrSignal?: SessionListProgress | AbortSignal,
		signal?: AbortSignal,
	): Promise<SessionInfo[]> {
		const customSessionDir =
			typeof sessionDirOrOnProgress === "string" ? normalizePath(sessionDirOrOnProgress) : undefined;
		const progress =
			typeof sessionDirOrOnProgress === "function"
				? sessionDirOrOnProgress
				: typeof onProgressOrSignal === "function"
					? onProgressOrSignal
					: undefined;
		const abortSignal =
			typeof sessionDirOrOnProgress === "string" || typeof onProgressOrSignal === "function"
				? signal
				: (onProgressOrSignal ?? signal);
		abortSignal?.throwIfAborted();
		const dir = customSessionDir ?? getDefaultAgentDir();
		const databasePath = getSessionDatabasePath(customSessionDir);
		const sessions = await readSessionInfos(databasePath, dir, undefined, progress, abortSignal);
		publishSessionList(sessions, progress, abortSignal, ALL_SESSION_LIST_PUBLISH_INTERVAL);
		return sortSessionInfos(sessions);
	}
}
